require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MyHikesController do

  # This should return the minimal set of attributes required to create a valid
  # MyHike. As you add validations to MyHike, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "hike_name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MyHikesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all my_hikes as @my_hikes" do
      my_hike = MyHike.create! valid_attributes
      get :index, {}, valid_session
      assigns(:my_hikes).should eq([my_hike])
    end
  end

  describe "GET show" do
    it "assigns the requested my_hike as @my_hike" do
      my_hike = MyHike.create! valid_attributes
      get :show, {:id => my_hike.to_param}, valid_session
      assigns(:my_hike).should eq(my_hike)
    end
  end

  describe "GET new" do
    it "assigns a new my_hike as @my_hike" do
      get :new, {}, valid_session
      assigns(:my_hike).should be_a_new(MyHike)
    end
  end

  describe "GET edit" do
    it "assigns the requested my_hike as @my_hike" do
      my_hike = MyHike.create! valid_attributes
      get :edit, {:id => my_hike.to_param}, valid_session
      assigns(:my_hike).should eq(my_hike)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new MyHike" do
        expect {
          post :create, {:my_hike => valid_attributes}, valid_session
        }.to change(MyHike, :count).by(1)
      end

      it "assigns a newly created my_hike as @my_hike" do
        post :create, {:my_hike => valid_attributes}, valid_session
        assigns(:my_hike).should be_a(MyHike)
        assigns(:my_hike).should be_persisted
      end

      it "redirects to the created my_hike" do
        post :create, {:my_hike => valid_attributes}, valid_session
        response.should redirect_to(MyHike.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved my_hike as @my_hike" do
        # Trigger the behavior that occurs when invalid params are submitted
        MyHike.any_instance.stub(:save).and_return(false)
        post :create, {:my_hike => { "hike_name" => "invalid value" }}, valid_session
        assigns(:my_hike).should be_a_new(MyHike)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        MyHike.any_instance.stub(:save).and_return(false)
        post :create, {:my_hike => { "hike_name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested my_hike" do
        my_hike = MyHike.create! valid_attributes
        # Assuming there are no other my_hikes in the database, this
        # specifies that the MyHike created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        MyHike.any_instance.should_receive(:update).with({ "hike_name" => "MyString" })
        put :update, {:id => my_hike.to_param, :my_hike => { "hike_name" => "MyString" }}, valid_session
      end

      it "assigns the requested my_hike as @my_hike" do
        my_hike = MyHike.create! valid_attributes
        put :update, {:id => my_hike.to_param, :my_hike => valid_attributes}, valid_session
        assigns(:my_hike).should eq(my_hike)
      end

      it "redirects to the my_hike" do
        my_hike = MyHike.create! valid_attributes
        put :update, {:id => my_hike.to_param, :my_hike => valid_attributes}, valid_session
        response.should redirect_to(my_hike)
      end
    end

    describe "with invalid params" do
      it "assigns the my_hike as @my_hike" do
        my_hike = MyHike.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MyHike.any_instance.stub(:save).and_return(false)
        put :update, {:id => my_hike.to_param, :my_hike => { "hike_name" => "invalid value" }}, valid_session
        assigns(:my_hike).should eq(my_hike)
      end

      it "re-renders the 'edit' template" do
        my_hike = MyHike.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MyHike.any_instance.stub(:save).and_return(false)
        put :update, {:id => my_hike.to_param, :my_hike => { "hike_name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested my_hike" do
      my_hike = MyHike.create! valid_attributes
      expect {
        delete :destroy, {:id => my_hike.to_param}, valid_session
      }.to change(MyHike, :count).by(-1)
    end

    it "redirects to the my_hikes list" do
      my_hike = MyHike.create! valid_attributes
      delete :destroy, {:id => my_hike.to_param}, valid_session
      response.should redirect_to(my_hikes_url)
    end
  end

end
